### ISSUE TITLE
"You do not have access to the wiki" for official project home URL

### ISSUE THREAD

**Issue by hartwork** [williambernardet/japi-checker#2]
On https://bitbucket.org/williambernardet/japi-checker/wiki/Home I read:

> You do not have access to the wiki.

Does the URL need an update?

**Comment by williambernardet** [comment]
Yep, I did not yet had time yet to transfer everything from code.google.com project. I'll do it as soon as I came back from vacation.

**Comment by williambernardet** [comment]
I've now fully moved the project on github and fixed the links in the Readme.md file.

**Comment by hartwork** [comment]
Okay, thanks!
